apiVersion: apps/v1
kind: Deployment
metadata:
  name: exercise
  labels:
    app: exercise
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exercise
  template:
    metadata:
      labels:
        app: exercise
    spec:
      containers:
      - name: exercise
        image: hjsky1010/exercise:dev
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: DB_SERVER
          valueFrom:
            configMapKeyRef:
              name: starfit-config
              key: DB_SERVER
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: starfit-config
              key: DB_PORT
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: starfit-config
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: starfit-config
              key: DB_PASSWORD
        - name: SERVLET_CONTEXT_PATH
          valueFrom:
            configMapKeyRef:
              name: starfit-config
              key: SERVLET_CONTEXT_PATH
