apiVersion: apps/v1
kind: Deployment
metadata:
  name: starfit
  labels:
    app: starfit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: starfit
  template:
    metadata:
      labels:
        app: starfit
    spec:
      containers:
      - name: starfit
        image: stfantasy3324/starfit:dev
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: DB_SERVER
          valueFrom:
            configMapKeyRef:
              name: sample-config
              key: DB_SERVER
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: sample-config
              key: DB_PORT
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: sample-config
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: sample-config
              key: DB_PASSWORD
        - name: SERVLET_CONTEXT_PATH
          valueFrom:
            configMapKeyRef:
              name: sample-config
              key: SERVLET_CONTEXT_PATH
